-- Telemetry tables used by the MATA ESP32 firmware and web dashboard.
create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  device_id text not null,
  ts timestamptz not null default now(),
  created_at timestamptz not null default now(),
  voltage_v numeric,
  voltage_status text,
  current_a numeric,
  active_power_w numeric,
  apparent_power_va numeric,
  apparent_power_kva numeric,
  reactive_power_var numeric,
  power_factor numeric,
  pf_status text,
  frequency_hz numeric,
  freq_status text,
  utilization_pct numeric,
  load_status text,
  temperature_c numeric,
  temp_rise_k numeric,
  temp_status text,
  fault_type text,
  sms_alerts_enabled boolean
);

alter table public.readings add column if not exists created_at timestamptz;
alter table public.readings alter column created_at set default now();

create table if not exists public.device_status (
  device_id text primary key,
  status text,
  last_seen timestamptz not null default now()
);

create table if not exists public.gps_log (
  id bigint generated by default as identity primary key,
  device_id text not null,
  ts timestamptz not null default now(),
  latitude double precision not null,
  longitude double precision not null
);

create table if not exists public.gps_status (
  device_id text primary key,
  gps_valid boolean not null default false,
  gps_hardware_error boolean not null default false,
  last_data_ms bigint,
  ts timestamptz not null default now(),
  latitude double precision,
  longitude double precision
);

create index if not exists readings_device_ts_idx on public.readings (device_id, ts desc);
create index if not exists gps_log_device_ts_idx on public.gps_log (device_id, ts desc);

alter table public.readings enable row level security;
alter table public.device_status enable row level security;
alter table public.gps_log enable row level security;
alter table public.gps_status enable row level security;

-- The device uses the anon key, so inserts must be allowed. Reads are limited
-- to the dashboard's public anon client; use authenticated policies for a
-- production operator login.
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'readings' and policyname = 'MATA anon insert readings') then
    create policy "MATA anon insert readings" on public.readings for insert to anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'readings' and policyname = 'MATA anon read readings') then
    create policy "MATA anon read readings" on public.readings for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'device_status' and policyname = 'MATA anon write device status') then
    create policy "MATA anon write device status" on public.device_status for insert to anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'device_status' and policyname = 'MATA anon read device status') then
    create policy "MATA anon read device status" on public.device_status for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'device_status' and policyname = 'MATA anon update device status') then
    create policy "MATA anon update device status" on public.device_status for update to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'gps_log' and policyname = 'MATA anon insert gps log') then
    create policy "MATA anon insert gps log" on public.gps_log for insert to anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'gps_log' and policyname = 'MATA anon read gps log') then
    create policy "MATA anon read gps log" on public.gps_log for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'gps_status' and policyname = 'MATA anon write gps status') then
    create policy "MATA anon write gps status" on public.gps_status for insert to anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'gps_status' and policyname = 'MATA anon read gps status') then
    create policy "MATA anon read gps status" on public.gps_status for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'gps_status' and policyname = 'MATA anon update gps status') then
    create policy "MATA anon update gps status" on public.gps_status for update to anon using (true) with check (true);
  end if;
end $$;

grant select, insert, update on public.readings, public.device_status, public.gps_log, public.gps_status to anon;